CONNECT QLCONGTY/DOAN;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

--AUDIT
--A. CẬP NHẬT TRƯỜNG THOIGIAN TRONG QUAN HỆ PHANCONG
BEGIN
  DBMS_FGA.drop_policy(
    OBJECT_SCHEMA => 'QLCONGTY',
    OBJECT_NAME => 'PHANCONG',
    POLICY_NAME => 'CHANGETIME'
    );
END;
/
BEGIN 
 DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA => 'QLCONGTY',
    OBJECT_NAME => 'PHANCONG',
    POLICY_NAME => 'CHANGETIME',
    AUDIT_COLUMN => 'THOIGIAN',
    ENABLE => TRUE,
    STATEMENT_TYPES => 'UPDATE',
    AUDIT_COLUMN_OPTS => DBMS_FGA.ALL_COLUMNS
    );
END;
/
--B. ĐỌC TRÊN TRƯỜNG LUONG VÀ PHUC CAP CỦA NGƯỜI KHÁC
BEGIN
  DBMS_FGA.drop_policy(
    OBJECT_SCHEMA => 'QLCONGTY',
    OBJECT_NAME => 'NHANVIEN',
    POLICY_NAME => 'CHANGE_LP'
    );
END;
/
BEGIN 
 DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA => 'QLCONGTY',
    OBJECT_NAME => 'NHANVIEN',
    POLICY_NAME => 'CHANGE_LP',
    AUDIT_COLUMN => 'LUONG, PHUCAP',
    AUDIT_CONDITION => 'MANV != ''' || SYS_CONTEXT('USERENV', 'SESSION_USER') || '''',
    ENABLE => TRUE,
    STATEMENT_TYPES => 'SELECT',
    AUDIT_COLUMN_OPTS => DBMS_FGA.ALL_COLUMNS
    );
END;
/

--C. KHÔNG THUỘC VAI TRÒ TÀI CHÍNH NHƯNG CẬP NHẬT THÀNH CÔNG TRÊN TRƯỜNG LƯƠNG VÀ PHỤ CẤP
BEGIN
  DBMS_FGA.drop_policy(
    OBJECT_SCHEMA => 'QLCONGTY',
    OBJECT_NAME => 'NHANVIEN',
    POLICY_NAME => 'CHANGENHANVIEN'
    );
END;
/
BEGIN 
 DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA => 'QLCONGTY',
    OBJECT_NAME => 'NHANVIEN',
    POLICY_NAME => 'CHANGENHANVIEN',
    AUDIT_COLUMN => 'LUONG,PHUCAP',
    AUDIT_CONDITION => SYS_CONTEXT('USERENV', 'SESSION_USER') || ' NOT LIKE (TC%)',
    ENABLE => TRUE,
    STATEMENT_TYPES => 'UPDATE',
    AUDIT_COLUMN_OPTS => DBMS_FGA.ALL_COLUMNS
    );
END;
/