CONNECT QLCONGTY/DOAN;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- FUNCTION TẠO USERID KHI ADD
CREATE OR REPLACE FUNCTION CREATE_USERID(
    USEROLE NVARCHAR2
)
RETURN CHAR
IS
    IDUSER CHAR(5);
    COUNTIN INT;
BEGIN
   IF(USEROLE LIKE 'Nhân viên') THEN
        BEGIN
            SELECT COUNT(*) INTO COUNTIN FROM QLCONGTY.NHANVIEN WHERE MANV LIKE 'NV%';
            IF(COUNTIN = 0) THEN IDUSER := 'NV001';
            ELSE SELECT 'NV' || TO_CHAR(TO_NUMBER(SUBSTR(MAX(MANV), 3)) + 1, 'FM000') INTO IDUSER FROM QLCONGTY.NHANVIEN WHERE MANV LIKE 'NV%';
            END IF; 
        END;
    ELSIF(USEROLE LIKE 'Quản lý trực tiếp') THEN
        BEGIN
            SELECT COUNT(*) INTO COUNTIN FROM QLCONGTY.NHANVIEN WHERE MANV LIKE 'QL%';
            IF(COUNTIN = 0) THEN IDUSER := 'QL001';
            ELSE SELECT 'QL' || TO_CHAR(TO_NUMBER(SUBSTR(MAX(MANV), 3)) + 1, 'FM000') INTO IDUSER FROM QLCONGTY.NHANVIEN WHERE MANV LIKE 'QL%';
            END IF; 
        END;
    ELSIF(USEROLE LIKE 'Trưởng phòng') THEN
        BEGIN
            SELECT COUNT(*) INTO COUNTIN FROM QLCONGTY.NHANVIEN WHERE MANV LIKE 'TP%';
            IF(COUNTIN = 0) THEN IDUSER := 'TP001';
            ELSE SELECT 'TP' || TO_CHAR(TO_NUMBER(SUBSTR(MAX(MANV), 3)) + 1, 'FM000') INTO IDUSER FROM QLCONGTY.NHANVIEN WHERE MANV LIKE 'TP%';
            END IF; 
        END;
    ELSIF(USEROLE LIKE 'Tài chính') THEN
        BEGIN
            SELECT COUNT(*) INTO COUNTIN FROM QLCONGTY.NHANVIEN WHERE MANV LIKE 'TC%';
            IF(COUNTIN = 0) THEN IDUSER := 'TC001';
            ELSE SELECT 'TC' || TO_CHAR(TO_NUMBER(SUBSTR(MAX(MANV), 3)) + 1, 'FM000') INTO IDUSER FROM QLCONGTY.NHANVIEN WHERE MANV LIKE 'TC%';
            END IF; 
        END;
     ELSIF(USEROLE LIKE 'Nhân sự') THEN
        BEGIN
            SELECT COUNT(*) INTO COUNTIN FROM QLCONGTY.NHANVIEN WHERE MANV LIKE 'NS%';
            IF(COUNTIN = 0) THEN IDUSER := 'NS001';
            ELSE SELECT 'NS' || TO_CHAR(TO_NUMBER(SUBSTR(MAX(MANV), 3)) + 1, 'FM000') INTO IDUSER FROM QLCONGTY.NHANVIEN WHERE MANV LIKE 'NS%';
            END IF; 
        END;
    ELSIF(USEROLE LIKE 'Trưởng đề án') THEN
        BEGIN
            SELECT COUNT(*) INTO COUNTIN FROM QLCONGTY.NHANVIEN WHERE MANV LIKE 'TA%';
            IF(COUNTIN = 0) THEN IDUSER := 'TA001';
            ELSE SELECT 'TA' || TO_CHAR(TO_NUMBER(SUBSTR(MAX(MANV), 3)) + 1, 'FM000') INTO IDUSER FROM QLCONGTY.NHANVIEN WHERE MANV LIKE 'TA%';
            END IF; 
        END;
    END IF;
    RETURN IDUSER;
END;
/
-- FUNCTION TẠO PROJECTID KHI ADD
CREATE OR REPLACE FUNCTION CREATE_PROJECTID
RETURN CHAR
IS
    NEWID CHAR(5);
    COUNTIN INT;
BEGIN
     SELECT COUNT(*) INTO COUNTIN FROM QLCONGTY.DEAN;
     IF(COUNTIN = 0) THEN NEWID := 'DA001';
     ELSE SELECT 'DA' || TO_CHAR(TO_NUMBER(SUBSTR(MAX(MADA), 3)) + 1, 'FM000') INTO NEWID FROM QLCONGTY.DEAN;
     END IF;       
     RETURN NEWID;
END;
/
-- FUNCTION TẠO DEPARTMENTID KHI ADD
CREATE OR REPLACE FUNCTION CREATE_DEPARTMENTID
RETURN CHAR
IS
    NEWID INT;
    COUNTIN INT;
BEGIN
     SELECT COUNT(*) INTO COUNTIN FROM QLCONGTY.PHONGBAN;
     IF(COUNTIN = 0) THEN NEWID := 1;
     ELSE SELECT MAX(MAPB) + 1 INTO NEWID FROM QLCONGTY.PHONGBAN;
     END IF;       
     RETURN NEWID;
END;
/



