CONNECT QLCONGTY/DOAN;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- YÊU CẦU 3. TẠO MỚI, XÓA, SỬA USER/ROLE
-- TẠO MỚI USER 
CREATE OR REPLACE PROCEDURE CREATE_USER(
    USER_NAME IN NVARCHAR2, 
    PASS IN NVARCHAR2
)
AS
    TMP_COUNT INT;
BEGIN
    SELECT COUNT(*) INTO TMP_COUNT 
    FROM ALL_USERS 
    WHERE USERNAME = USER_NAME;
    
    IF(TMP_COUNT != 0) THEN
        BEGIN
            RAISE_APPLICATION_ERROR(-20000,N'USER ĐÃ TỒN TẠI!'); 
        END;
    ELSE 
        BEGIN
            EXECUTE IMMEDIATE('ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE');
            EXECUTE IMMEDIATE('CREATE USER '|| USER_NAME||' IDENTIFIED BY '||PASS);
            EXECUTE IMMEDIATE('GRANT CREATE SESSION TO '||USER_NAME);
        END;
    END IF;
END;
/

-- XÓA USER
CREATE OR REPLACE PROCEDURE DROP_USER(
    USER_NAME IN NVARCHAR2
)
AS
    TMP_COUNT INT;
BEGIN
    SELECT COUNT(*) INTO TMP_COUNT 
    FROM ALL_USERS 
    WHERE USERNAME = USER_NAME;
    
    IF(TMP_COUNT != 0) THEN
        BEGIN
            EXECUTE IMMEDIATE('ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE');
            EXECUTE IMMEDIATE('DROP USER '|| USER_NAME);
        END;
    ELSE 
         RAISE_APPLICATION_ERROR(-20000,N'USER KHÔNG TỒN TẠI'); 
    END IF;
END;
/

-- SỬA (HIỆU CHỈNH) USER
CREATE OR REPLACE PROCEDURE CHANGE_PASS_USER(
    USER_NAME IN VARCHAR2,
    NEWPASS IN VARCHAR2
)
AS
    TMP_COUNT INT;
BEGIN
    SELECT COUNT(*) INTO TMP_COUNT 
    FROM ALL_USERS 
    WHERE USERNAME = USER_NAME;
    
    IF(TMP_COUNT != 0) THEN
        BEGIN
            EXECUTE IMMEDIATE('ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE');
            EXECUTE IMMEDIATE('ALTER USER '|| USER_NAME||' IDENTIFIED BY '||NEWPASS);
        END;
    ELSE 
            RAISE_APPLICATION_ERROR(-20000,'USER KHÔNG TỒN TẠI!'); 
    END IF;
END;
/

-- TẠO ROLE MỚI
CREATE OR REPLACE PROCEDURE CREATE_ROLE(
    ROLENAME IN VARCHAR2
)
AS
    TMP_COUNT INT;
BEGIN
    SELECT COUNT(*) INTO TMP_COUNT 
    FROM DBA_ROLES 
    WHERE ROLE = ROLENAME;
    
    IF(TMP_COUNT != 0) THEN
        BEGIN
            RAISE_APPLICATION_ERROR(-20000,N'ROLE ĐÃ TỒN TẠI!'); 
        END;
    ELSE 
        BEGIN
            EXECUTE IMMEDIATE('ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE');
            EXECUTE IMMEDIATE('CREATE ROLE '|| ROLENAME);
        END;
    END IF;
End;
/

-- XÓA ROLE
CREATE OR REPLACE PROCEDURE  DROP_ROLE(
    ROLENAME IN VARCHAR2
)
AS
    TMP_COUNT INT;
BEGIN
    SELECT COUNT(*) INTO TMP_COUNT 
    FROM DBA_ROLES 
    WHERE ROLE = ROLENAME;
    
    IF(TMP_COUNT != 0) THEN
        BEGIN
            EXECUTE IMMEDIATE('ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE');
            EXECUTE IMMEDIATE('DROP ROLE '|| ROLENAME);
        END;
    ELSE 
        BEGIN
            RAISE_APPLICATION_ERROR(-20000,N'ROLE KHÔNG TỒN TẠI!'); 
        END;
    END IF;
END;
/