CONNECT QLCONGTY/DOAN;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- YÊU CẦU 1 - XEM DANH SÁCH ĐỐI TƯỢNG NGƯỜI DÙNG TRONG HỆ THỐNG
-- XEM DANH SÁCH USER
CREATE OR REPLACE PROCEDURE LIST_USER
AS
RESULTS SYS_REFCURSOR;
BEGIN
    OPEN RESULTS FOR
    SELECT USERNAME FROM DBA_USERS
    WHERE ACCOUNT_STATUS != 'LOCKED'
    AND USERNAME NOT IN ('QLCONGTY','SYSRAC','SYSTEM')
    ORDER BY USERNAME;
    DBMS_SQL.RETURN_RESULT(RESULTS);
END;
/

--XEM DANH SÁCH ROLE
CREATE OR REPLACE PROCEDURE LIST_ROLE
AS
RESULTS SYS_REFCURSOR;
BEGIN 
    OPEN RESULTS FOR
    SELECT RL.GRANTED_ROLE AS ROLENAME
    FROM DBA_ROLES R
    JOIN DBA_ROLE_PRIVS RL
    ON R.ROLE = RL.GRANTED_ROLE
    WHERE RL.GRANTEE = 'QLCONGTY'
    AND RL.GRANTED_ROLE NOT IN ('DBA')
    ORDER BY RL.GRANTED_ROLE;
    DBMS_SQL.RETURN_RESULT(RESULTS);
END;
/