CONNECT QLCONGTY/DOAN;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- YÊU CẦU 4. CHO PHÉP THỰC HIỆN CẤP QUYỀN
-- FUNCTION KIỂM TRA USER/ROLE ĐÃ TỒN TẠI
CREATE OR REPLACE FUNCTION CHECK_UOR(
    UORNAME IN VARCHAR2
)
RETURN INT
AS
    COUNTUSER INT;
    COUNTROLE INT;
BEGIN
    SELECT COUNT(*) INTO COUNTUSER FROM ALL_USERS WHERE USERNAME = UORNAME;
    SELECT COUNT(*) INTO COUNTROLE FROM DBA_ROLES WHERE ROLE = UORNAME;
    IF(COUNTUSER != 0 OR COUNTROLE != 0) THEN
        RETURN 1;
    END IF;
    RETURN 0;
END;
/

-- CẤP ROLE CHO MỘT USER
CREATE OR REPLACE PROCEDURE GRANT_ROLE4USER(
    USERID IN VARCHAR2,
    ROLE_NAME IN VARCHAR2) 
IS
    RESULT_STR VARCHAR2(300);
BEGIN
    RESULT_STR:= 'GRANT ' || ROLE_NAME || ' TO ' || USERID;
    EXECUTE IMMEDIATE RESULT_STR; 
END;
/

-- CẤP QUYỀN CHO USER
CREATE OR REPLACE PROCEDURE GRANTPRI4USER(
    UORNAME IN VARCHAR2, 
    TABLENAME IN VARCHAR2,
    PRIV IN VARCHAR2,
    LISTCOLUMN IN SYS.ODCIVARCHAR2LIST,
    IS_WGO IN VARCHAR2
) 
IS
    L_COLUMN VARCHAR2(4000);
    RESULT_STR VARCHAR2(300);
    TABLE_NAME  VARCHAR2(50);
    COUNTUOR INT;
BEGIN
    FOR VAL IN 1..LISTCOLUMN.COUNT LOOP
        L_COLUMN := L_COLUMN || LISTCOLUMN(VAL) || ',';
    END LOOP;
    L_COLUMN := RTRIM(L_COLUMN, ',');
    
    TABLE_NAME:='QLCONGTY.'||TABLENAME;
    SELECT CHECK_UOR(UORNAME) INTO COUNTUOR FROM DUAL;
    IF(COUNTUOR != 0) THEN
        BEGIN
            IF(PRIV = 'SELECT') THEN
                BEGIN
                    IF L_COLUMN IS NOT NULL THEN
                        RESULT_STR := 'CREATE OR REPLACE VIEW ' || TABLE_NAME || '_' || UORNAME || ' AS '|| ' SELECT ' || L_COLUMN || ' FROM ' || TABLE_NAME;
                        EXECUTE IMMEDIATE RESULT_STR;
                        RESULT_STR:= 'GRANT SELECT ON ' || TABLE_NAME || '_' || UORNAME|| ' TO ' ||UORNAME;
                    ELSE
                        RESULT_STR := 'GRANT SELECT ON ' || TABLE_NAME || ' TO ' ||UORNAME;
                    END IF;
                END;
            ELSIF (PRIV = 'UPDATE') THEN
                IF L_COLUMN IS NOT NULL THEN
                    RESULT_STR := 'GRANT UPDATE (' || L_COLUMN || ') ON ' || TABLE_NAME || ' TO ' || UORNAME;
                ELSE
                    RESULT_STR := 'GRANT UPDATE ON ' || TABLE_NAME || ' TO ' || UORNAME;
                END IF;
            ELSE 
                BEGIN
                    RESULT_STR:= 'GRANT ' || PRIV || ' ON ' || TABLE_NAME || ' TO ' || UORNAME;
                END;
            END IF;
            
            IF(IS_WGO = 'YES') THEN
                RESULT_STR := RESULT_STR ||' WITH GRANT OPTION';
            END IF;
        END;
    ELSE
        BEGIN
            RAISE_APPLICATION_ERROR(-20000,N'USER KHÔNG TỒN TẠI'); 
        END;
    END IF;
    EXECUTE IMMEDIATE RESULT_STR;
END;
/

-- CẤP QUYỀN CHO MỘT ROLE
CREATE OR REPLACE PROCEDURE GRANTPRI4ROLE(
    UORNAME IN VARCHAR2, 
    TABLENAME IN VARCHAR2,
    PRIV IN VARCHAR2,
    LISTCOLUMN IN SYS.ODCIVARCHAR2LIST
) 
IS
    L_COLUMN VARCHAR2(4000);
    RESULT_STR VARCHAR2(300);
    TABLE_NAME  VARCHAR2(50);
    COUNTUOR INT;
BEGIN
    FOR VAL IN 1..LISTCOLUMN.COUNT LOOP
        L_COLUMN := L_COLUMN || LISTCOLUMN(VAL) || ',';
    END LOOP;
    L_COLUMN := RTRIM(L_COLUMN, ',');
    
    TABLE_NAME:='QLCONGTY.'||TABLENAME;
    SELECT CHECK_UOR(UORNAME) INTO COUNTUOR FROM DUAL;
    IF(COUNTUOR != 0) THEN
        BEGIN
            IF(PRIV = 'SELECT') THEN
                BEGIN
                    IF L_COLUMN IS NOT NULL THEN
                        RESULT_STR := 'CREATE OR REPLACE VIEW ' || TABLE_NAME || '_' || UORNAME || ' AS '|| ' SELECT ' || L_COLUMN || ' FROM ' || TABLE_NAME;
                        EXECUTE IMMEDIATE RESULT_STR;
                        RESULT_STR:= 'GRANT SELECT ON ' || TABLE_NAME || '_' || UORNAME|| ' TO ' ||UORNAME;
                    ELSE
                        RESULT_STR := 'GRANT SELECT ON ' || TABLE_NAME || ' TO ' ||UORNAME;
                    END IF;
                END;
            ELSIF (PRIV = 'UPDATE') THEN
                IF L_COLUMN IS NOT NULL THEN
                    RESULT_STR := 'GRANT UPDATE (' || L_COLUMN || ') ON ' || TABLE_NAME || ' TO ' || UORNAME;
                ELSE
                    RESULT_STR := 'GRANT UPDATE ON ' || TABLE_NAME || ' TO ' || UORNAME;
                END IF;
            ELSE 
                BEGIN
                    RESULT_STR:= 'GRANT ' || PRIV || ' ON ' || TABLE_NAME || ' TO ' || UORNAME;
                END;
            END IF;
        END;
    ELSE
        BEGIN
            RAISE_APPLICATION_ERROR(-20000,N'USER KHÔNG TỒN TẠI'); 
        END;
    END IF;
    EXECUTE IMMEDIATE RESULT_STR;
END;
/

-- YÊU CẦU 5. THU HỒI QUYỀN
-- REVOKE QUYỀN CỦA MỘT USER/ROLE
CREATE OR REPLACE PROCEDURE REVOKE_USER (
    UORNAME IN VARCHAR2,
    PRIV IN VARCHAR2,
    TABLE_NAME IN VARCHAR2
)
AS
    TMP_COUNT INT;
    TABLENAME VARCHAR2(50);
BEGIN

    TABLENAME:='QLCONGTY.'||TABLE_NAME;
    
    SELECT CHECK_UOR(UORNAME) INTO TMP_COUNT FROM DUAL;
    IF(TMP_COUNT != 0) THEN
        EXECUTE IMMEDIATE ('REVOKE ' || PRIV || ' ON ' || TABLENAME || ' FROM ' || UORNAME);
    ELSE 
        RAISE_APPLICATION_ERROR(-20000, 'USER KHÔNG TỒN TẠI!'); 
    END IF;
END;
/