ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

DROP USER QLCONGTY CASCADE;

CREATE USER QLCONGTY IDENTIFIED BY DOAN;
GRANT CREATE SESSION TO QLCONGTY;
GRANT ALL PRIVILEGES TO QLCONGTY;
GRANT SYSDBA TO QLCONGTY;
GRANT EXECUTE ON DBMS_RLS TO QLCONGTY;
GRANT EXECUTE ON DBMS_CRYPTO TO QLCONGTY;
GRANT SELECT ON DBA_FGA_AUDIT_TRAIL TO QLCONGTY;
GRANT CONNECT, RESOURCE, DBA TO QLCONGTY;
GRANT UNLIMITED TABLESPACE TO QLCONGTY;
GRANT SELECT ON DBA_AUDIT_POLICIES TO QLCONGTY;
GRANT SELECT ON DBA_POLICIES TO QLCONGTY;

GRANT ALL PRIVILEGES TO QLCONGTY WITH ADMIN OPTION;
GRANT SELECT ON SYS.V_$INSTANCE TO QLCONGTY;
GRANT SELECT ON DBA_VIEWS TO QLCONGTY; 
GRANT SELECT ON DBA_TAB_COLUMNS TO QLCONGTY;

GRANT SELECT ON DBA_ROLES TO QLCONGTY; 
GRANT SELECT ON DBA_SYS_PRIVS TO QLCONGTY; 
GRANT SELECT ON DBA_TAB_PRIVS TO QLCONGTY; 
GRANT SELECT ON ROLE_TAB_PRIVS TO QLCONGTY; 
GRANT SELECT ON DBA_ROLE_PRIVS TO QLCONGTY;  
GRANT SELECT ON DBA_USERS TO QLCONGTY; 
GRANT SELECT ON DBA_COL_PRIVS TO QLCONGTY; 

CONNECT QLCONGTY/DOAN; 

CREATE TABLE QLCONGTY.KEY_ENCRYPT(
    ID_ENCRYPT INT,
    KEY NVARCHAR2(2000),
    
    CONSTRAINT PK_KEY PRIMARY KEY (ID_ENCRYPT)
);

CREATE TABLE QLCONGTY.NHANVIEN(
    MANV CHAR(5),
    TENNV NVARCHAR2(30),
    PHAI NVARCHAR2(3),
    NGAYSINH DATE,
    DIACHI NVARCHAR2(50),
    SODT CHAR(10),
    LUONG NVARCHAR2(2000),
    PHUCAP NVARCHAR2(2000),
    VAITRO NVARCHAR2(15),
    MANQL CHAR(5),
    PHG INT,
    
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
);
ALTER TABLE QLCONGTY.NHANVIEN ADD REGION NVARCHAR2(10);
ALTER TABLE QLCONGTY.NHANVIEN ADD FIELDNHANVIEN NVARCHAR2(20);
CREATE TABLE QLCONGTY.PHONGBAN(
    MAPB INT,
    TENPB NVARCHAR2(50),
    TRPHG CHAR(5),
    
    CONSTRAINT PK_PHONG PRIMARY KEY (MAPB)
);

CREATE TABLE QLCONGTY.DEAN(
    MADA CHAR(6),
    TENDA NVARCHAR2(50),
    NGAYBD DATE,
    PHONG INT,
    
    CONSTRAINT PK_DEAN PRIMARY KEY (MADA)
);

CREATE TABLE QLCONGTY.PHANCONG(
    MANV CHAR(5),
    MADA CHAR(6),
    THOIGIAN DATE,
    
    CONSTRAINT PK_PHANCONG PRIMARY KEY (MANV,MADA)
);

ALTER TABLE QLCONGTY.NHANVIEN
ADD CONSTRAINT FK_NQL
FOREIGN KEY (MANQL)
REFERENCES QLCONGTY.NHANVIEN(MANV);

ALTER TABLE QLCONGTY.NHANVIEN
ADD CONSTRAINT FK_NV_PHONG
FOREIGN KEY (PHG)
REFERENCES QLCONGTY.PHONGBAN(MAPB);

ALTER TABLE QLCONGTY.PHONGBAN
ADD CONSTRAINT FK_TP_PHONG
FOREIGN KEY (TRPHG)
REFERENCES QLCONGTY.NHANVIEN(MANV);

ALTER TABLE QLCONGTY.DEAN
ADD CONSTRAINT FK_DA_PHONG
FOREIGN KEY (PHONG)
REFERENCES QLCONGTY.PHONGBAN(MAPB);

ALTER TABLE QLCONGTY.PHANCONG
ADD CONSTRAINT FK_PC_DA
FOREIGN KEY (MADA)
REFERENCES QLCONGTY.DEAN(MADA);

ALTER TABLE QLCONGTY.PHANCONG
ADD CONSTRAINT FK_PC_NV
FOREIGN KEY (MANV)
REFERENCES QLCONGTY.NHANVIEN(MANV);